# This compose file is used for development/debugging
#
# Run with
# docker-compose -f docker-compose.yml -f  docker-compose.dev.yml up -d
# Properties defined here will override the ones defined on the main docker-compose file.
version: '3'

services:
  webapi:
    ports:
      - ${PORT}:${PORT}
      - "9229:9229"
    # The bellow command will allow us to debug using chrome inspector:
    # URL: chrome://inspect/#devices
    # Then select the nodejs process, and it will automatically pause
    # on the first line of execution.
    command:
      - node
      - "--inspect-brk=0.0.0.0"
      - "." 
